In [4]:
import cv2
import numpy as np
from matplotlib import pyplot as plt

In [5]:
%matplotlib inline

In [6]:
img_dep=cv2.imread('deep.jpg',cv2.G)
img_bgr=cv2.imread('bgr.jpg')

In [9]:
print(img_dep.shape,img_dep)

(160, 160, 3) [[[146 146 146]
  [142 142 142]
  [142 142 142]
  ..., 
  [  0   0   0]
  [  0   0   0]
  [118 118 118]]

 [[141 141 141]
  [142 142 142]
  [146 146 146]
  ..., 
  [  3   3   3]
  [118 118 118]
  [119 119 119]]

 [[142 142 142]
  [147 147 147]
  [144 144 144]
  ..., 
  [116 116 116]
  [116 116 116]
  [116 116 116]]

 ..., 
 [[ 60  60  60]
  [ 60  60  60]
  [ 60  60  60]
  ..., 
  [ 63  63  63]
  [ 63  63  63]
  [ 63  63  63]]

 [[ 60  60  60]
  [ 60  60  60]
  [ 60  60  60]
  ..., 
  [ 62  62  62]
  [ 62  62  62]
  [ 62  62  62]]

 [[ 60  60  60]
  [ 60  60  60]
  [ 60  60  60]
  ..., 
  [ 61  61  61]
  [ 61  61  61]
  [ 61  61  61]]]
